name: Uplaod Tests
# This workflow runs tests related to file upload functionality.
on:
    push:
        branches:
            - 'file-uploader-feature'
    pull_request:
        branches:
            - 'file-uploader-feature'

jobs:
    upload-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Run upload tests
              run: npm test -- --coverage --watchAll=false